### ISSUE TITLE
Offset on draft doesn't work

### ISSUE THREAD

**Issue by albertobissacco** [tumblr/tumblr_client#49]
```
#Controller
def draft
 @posts = @client.draft(params[:blog_name], :offset => params[:offset])
end
```
the offset parameter it seem not working. For example if i get this url address:
www.mywebsite.com/blog/blog_name/draft?offset=100
i have always the same results without the offset.

**Comment by albertobissacco** [comment]
#50 draft accept `before_id` param and not `offset`.

**Comment by meissadia** [comment]
Any chance this fix will be merged? I have the fix implemented on my machine but would like users of my own project, based on this gem, to not have to hack anything. Thanks!
