### ISSUE TITLE
uninitialized constant Tumblr 

### ISSUE THREAD

**Issue by chrishough** [tumblr/tumblr_client#51]
Here is my error: 
```
build.rb:5:in `<main>': uninitialized constant Tumblr (NameError)
```

Here is the file I am using:
```ruby
require 'rubygems'
require 'bundler/setup'

# Authenticate via OAuth
client = Tumblr::Client.new({
  :consumer_key => 'xxx',
  :consumer_secret => 'xxx',
  :oauth_token => 'xxx',
  :oauth_token_secret => 'xxx'
})

binding.pry

# Make the request
client.info
```
The `xxx` are replaced with values from Tumblr, and this is a straight ruby app. 

Thoughts?

**Comment by chrishough** [comment]
Ok, I fixed that first error by adding:
```
require 'tumblr/client'
```
but now I am getting:
```
/Users/chrishough/GrokTrunkLive/NoConformity/OpenSourceSoftware/my-projects/archive-tumblr/.bundle/ruby/2.2.0/gems/tumblr_client-0.8.5/lib/tumblr/client.rb:27:in `initialize': undefined method `options' for Tumblr:Module (NoMethodError)
	from build.rb:6:in `new'
	from build.rb:6:in `<main>'
```

**Comment by chrishough** [comment]
Fixed this issue with the following, meant to post this late last night:
```
require 'rubygems'
require 'pry'
require 'tumblr_client'
```

**Comment by cathleen5** [comment]
hacked acct

**Comment by chrishough** [comment]
@cathleen5 confused?

**Comment by ceykooo** [comment]
@chrishough For future reference, you don't need the `require 'rubygems'`. It's actually not even a [valid gem](https://rubygems.org/gems/rubygems) in the standard rubygems.org source. (Unless you've got another gem from elsewhere named `rubygems`, in which case ignore me.)

**Comment by chrishough** [comment]
@ceykooo thanks :+1:
